### ISSUE TITLE
Install instructions need to be updated for Varnish 4.0

### ISSUE THREAD

**Issue by daghf** [varnish/libvmod-example#6]
Since we no longer require the source to be available, and now use pkg-config to figure out the various paths.

**Comment by crico** [comment]
I am trying to install Varnish 4.0 on Squeeze but it seems that is no longer available in the repository, I would like to know why it is not already available.
I tried to compile the sources too, but get an error since there is no compatible curses library. 

Any ideas will be of great help, thanks.

**Comment by aondio** [comment]
@crico Hi, before compiling the source,have you checked if you have all the build dependencies and they are up-to-date?

**Comment by crico** [comment]
I execute the command: "./configure" with the following output:
...
checking for NcursesW wide-character library... no
checking for Ncurses library... no
checking for Curses library... no
configure: error: requires an X/Open-compatible Curses library

How do I can check dependencies?

**Comment by aondio** [comment]
@crico Before installing Varnish 4.0 from source you have to check de build dependencies listed here :https://www.varnish-cache.org/docs/4.0/installation/install.html

**Comment by crico** [comment]
Ok @aondio, thanks!

**Comment by PorterDon** [comment]
RBeaudoin, thanks much for the discrete steps in your Sept 26 comment. I am trying to tag along and get varnish and its related apps (like varnishstat, varnishtop, etc) correctly installed on my Raspberry Pi 2 running Jessie. At this point I have varnish running but must not be installed right because for "sudo /etc/init.d/varnish stop" I get "/etc/init.d/varnish: command not found". Your step #4 "Clone the git repo libvmod-example, and switch to the 'master' branch" is just a bit my antiquated vocabulary. Clone means copy, right? "Master branch"? I am trying to create a straightforward step-by-step varnish install (complete) for Raspbian. There have to be many people wanting to use varnish but are beyond intimidated by it's installation. Once installed and running we can fine-tune it etc and get our little Pi web servers greatly sped up. Thanks to you and others who can lend a hand.

**Comment by RBeaudoin** [comment]
You should take a look at the Git handbook to understand cloning and the
branching model:
http://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository

Basically you use the "git clone" command to copy a repository from a
remote server to your local machine. Once that is done, you can switch
branches via the "git checkout" command, so you'd run "git checkout master"
in your case.

Hope that helps, let me know if you have any other questions.

Rich

**Comment by lkarsten** [comment]
Should be completed now that @nigoroll 's pull requests are merged.
